# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve [--baseurl '']'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BTB Jekyll site
email: ijadams503@gmail.com
description: A static site for the BTB film using jekyll, gulp, sass, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "btb.ianjadams.com"

# Build settings
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]
gems:
    - jekyll-minifier
jekyll-minifier:
  exclude: ["assets/css/*.css","*.min.*"]
